# Nombre de la pipeline
name: MiPipelineReactAzure

# Trigger: Define qué eventos deben disparar la ejecución de la pipeline
trigger:
  branches:
    include:
      - main

# Definición de la pool de agentes (en este caso, se utiliza 'ubuntu-latest')
pool:
  vmImage: 'ubuntu-latest'

# Pasos de la pipeline
jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '14.x'

    - script: npm install
      displayName: 'Install Dependencies'

    - script: npm run build
      displayName: 'Build React App'
      
    - task: AzureWebApp@1
      displayName: 'Azure App Service Deploy'
      inputs:
        azureSubscription: 'Azure for Students'  # Cambiar por el nombre de tu suscripción de Azure
        appName: 'NotasPractica11'                  # Cambiar por el nombre de tu instancia de App Service
        package: $(Build.ArtifactStagingDirectory)/build
        appType: 'webApp'                             # Agregar esta línea para definir el tipo de aplicación
